### PR TITLE
redis deprecated zSize, Delete, setTimeout

### PR DESCRIPTION
**Pull request by zlmitchell**
1. Replace zSize() with zCard()
2. Replace delete() with del()
3. Replace setTimeout() with expire()

### CODE REVIEW

**Comment by soulseekah** [comment]
Thanks for your contribution. Do you have a specific deprecation timeline for these three commands?
When will each stop working? Since when does each of them work?

**Comment by zlmitchell** [comment]
in v5.0 Phpredis/redis deprecated delete(), zSize() and setTimeout() there are function that directly replace them.
  https://github.com/phpredis/phpredis/blob/5.0.0/redis.c
```
PHP_MALIAS(Redis, delete, del, arginfo_del, ZEND_ACC_PUBLIC | ZEND_ACC_DEPRECATED)
PHP_MALIAS(Redis, setTimeout, expire, arginfo_expire, ZEND_ACC_PUBLIC | ZEND_ACC_DEPRECATED)
PHP_MALIAS(Redis, zSize, zCard, arginfo_key, ZEND_ACC_PUBLIC | ZEND_ACC_DEPRECATED)
```
https://github.com/phpredis/phpredis/pull/1588 Commit -> https://github.com/phpredis/phpredis/commit/a81b4f2d

**Comment by soulseekah** [comment]
This was released 2 years ago, how deep has adoption been for the 5.x version?
Wouldn't it be safer to have a check in place if the methods do not exist use the old ones?
Or check library version to require 5.x+?
We wouldn't want hundreds of sites to break with a fatal error, would we?

**Comment by zlmitchell** [comment]
https://github.com/phpredis/phpredis/blob/4.0.0/redis.c

those command still exist in 4.0.0

**Comment by zlmitchell** [comment]
https://github.com/phpredis/phpredis/blob/3.0.0/redis.c

and 3.0.0

**Comment by soulseekah** [comment]
@kovshenin looks good?

**Comment by kovshenin** [comment]
Looks good to me.

**Pull request merged**
